/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

// /* @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
//const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
//};

//module.exports = sidebars;


module.exports = {
  aboutSidebar: [
     'about/ywam', 'about/ywamsendai', 'about/values', 'about/covenants', 'about/history', 'about/act', 'about/whyjapan', 'about/biblepoverty'
   ],
  communitySidebar: [
     'community/communication', 'community/commitments', 'community/friendshipwithgod',
      {
        type: 'category',
        label: 'Join',
        items: ['community/join', 'community/fundraising', 'community/payment', 'community/visaApply', 'community/visaRenew',]
      }
   ],
   lifeinjapanSidebar: [
     'lifeinjapan/gettingsettled', 'lifeinjapan/disaster', 'lifeinjapan/culture',
     {
       type: 'category',
       label: 'Japanese Language',
       items: ['lifeinjapan/language', 'lifeinjapan/language2', 'lifeinjapan/language3']
       }, 'lifeinjapan/phones', 'lifeinjapan/driving', 'lifeinjapan/money',
     {
       type: 'category',
       label: 'Japanese Tax',
       items: ['lifeinjapan/tax', 'lifeinjapan/tax2', 'lifeinjapan/tax3']
     }
   ],
   dtsSidebar: [
     'dts/apply', 'dts/faq'
   ]
}
